### ISSUE TITLE
Make a better publish-assets/copy-assets workflow

### ISSUE THREAD

**Issue by nchevobbe** [devtools-html/devtools-reps#60]
In https://github.com/devtools-html/devtools-reps/blob/master/bin/copy-assets.js we only copy `load-reps.js` and `reps.css` and make a bundle (https://github.com/devtools-html/devtools-reps/blob/master/bin/copy-assets.js#L29-L35). 
If I get this right, I think we should copy the `reps.js` file from assets into the `firefox` dir instead, since the bundle is already built in https://github.com/devtools-html/devtools-reps/blob/master/bin/publish-assets.js#L44-L49

**Comment by juliandescottes** [comment]
In theory this should be accomplished by makeBundle. (see the output path, which should target reps in the firefox checkout). Try sudo-ing if you have permission issues.

Which also makes me think that the two files we copy are taken from assets/build, which makes copy-assets dependent on publish-assets. But both scripts are creating the bundle, simply outputting it in different locations.

There's no real added value in doing the bundle twice. So we can either:
1 - make copy assets take load-reps.js and reps.css from source. This way publish-assets is no longer mandatory
2 - make copy assets copy reps.js rather than building it. publish-assets is still a mandatory first step but we no longer build the bundle twice

**Comment by juliandescottes** [comment]
@nchevobbe I think we can close this one actually now?

**Comment by nchevobbe** [comment]
Yep !
